dist: xenial

language: cpp

compiler:
  - gcc
  - clang

addons:
  sonarcloud:
    organization: "simpsont-oci-github"
    token:
      secure: "c0c2439632339ff95c5fbe6389930c8a8d1a3bda"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-program-options-dev
      - cmake

branches:
  only:
    - master

before_script:
  - cmake .

script:
  - sonar-scanner
  - make
