language: cpp

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libboost-program-options-dev
      - g++-8
      - cmake

branches:
  only:
    - master

before_script:
  - cmake .

script:
  - make
